# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :build do
    gym(
      scheme: "bitriseDemo",
      export_xcargs: "-allowProvisioningUpdates",
      export_method: "ad-hoc"
    )
end

  lane :firebase do
    firebase_app_distribution(
      app: "1:219005991539:ios:e3300bcfa9774e12808806",
      service_credentials_file: "firebaseServiceKey.json",
      testers: "nfinfu@gmail.com",
      release_notes: "Bitrise testflight release test"
    )
  end

  lane :build_and_deploy do |options|

    build
    firebase

  end

end
